[workspace]

members = [
    "core",
    "frontends/cli",
]

default-members = [
    "frontends/cli"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
